name: color_palette_generator
description: Color palette generator, capable to generate N colors using a set of basic colors. Supports HEX and RGBA colors.
version: 2.0.0
homepage: https://github.com/Colossus-Services/color_palette_generator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  swiss_knife: ^3.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
