name: color_palette_generator
description: Color palette generator, capable to generate N colors using a set of basic colors. Supports HEX and RGBA colors.
version: 2.0.1
homepage: https://github.com/Colossus-Services/color_palette_generator

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  swiss_knife: ^3.1.5

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.4
  dependency_validator: ^3.2.3
