name: color_palette_generator
description: Color palette generator, capable to generate N colors using a set of basic colors. Supports HEX and RGBA colors.
version: 1.0.3
homepage: https://github.com/Colossus-Services/color_palette_generator

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  swiss_knife: ^2.5.15
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.14.4
